CustomSFPath/force-app/main/default/objects/CustomPath__mdt/CustomPath__mdt.object-meta.xml
<CustomObject>
    <label>CustomPath</label>
    <pluralLabel>CustomPath</pluralLabel>
</CustomObject>

CustomSFPath/force-app/main/default/objects/CustomPath__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Détermine si le path est actif</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

CustomSFPath/force-app/main/default/objects/CustomPath__mdt/fields/StatusField__c.field-meta.xml
<CustomField>
    <fullName>StatusField__c</fullName>
    <label>StatusField</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CustomSFPath/force-app/main/default/objects/CustomPathFields__mdt/CustomPathFields__mdt.object-meta.xml
<CustomObject>
    <label>CustomPathFields</label>
    <pluralLabel>CustomPathFields</pluralLabel>
</CustomObject>

CustomSFPath/force-app/main/default/objects/CustomPathFields__mdt/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <label>FieldApiName</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

CustomSFPath/force-app/main/default/objects/CustomPathFields__mdt/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>CustomPathSteps</label>
    <referenceTo>CustomPathSteps__mdt</referenceTo>
    <relationshipLabel>CustomPathFields</relationshipLabel>
    <relationshipName>CustomPathFields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

CustomSFPath/force-app/main/default/objects/CustomPathSteps__mdt/CustomPathSteps__mdt.object-meta.xml
<CustomObject>
    <label>CustomPathSteps</label>
    <pluralLabel>CustomPathSteps</pluralLabel>
</CustomObject>

CustomSFPath/force-app/main/default/objects/CustomPathSteps__mdt/fields/GuideSelling__c.field-meta.xml
<CustomField>
    <fullName>GuideSelling__c</fullName>
    <label>GuideSelling</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

CustomSFPath/force-app/main/default/objects/CustomPathSteps__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>CustomPath</label>
    <referenceTo>CustomPath__mdt</referenceTo>
    <relationshipLabel>CustomPathSteps</relationshipLabel>
    <relationshipName>CustomPathSteps</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

CustomSFPath/force-app/main/default/objects/CustomPathSteps__mdt/fields/StepName__c.field-meta.xml
<CustomField>
    <fullName>StepName__c</fullName>
    <label>StepName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CustomSFPath/force-app/main/default/objects/CustomPathSteps__mdt/fields/StepNum__c.field-meta.xml
<CustomField>
    <fullName>StepNum__c</fullName>
    <description>Numéro de l&apos;étape</description>
    <label>StepNum</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CustomSFPath/force-app/main/default/classes/CustomPathController.cls
public with sharing class CustomPathController {


    //get objetct name from recordId
    @AuraEnabled(cacheable=true)
    public static String getObjectName(String recordIdString){
        // Assurez-vous que la chaîne d'ID n'est pas nulle et essayez de convertir en Id
        if (String.isBlank(recordIdString)) {
            return null;
        }

        Id recordId = Id.valueOf(recordIdString);

        // Obtient le type SObjectType de l'ID de l'enregistrement
        Schema.SObjectType objectType = recordId.getSObjectType();
        
        // Obtient la description de l'objet
        Schema.DescribeSObjectResult describeResult = objectType.getDescribe();
        
        // Retourne le nom de l'objet
        return describeResult.getName();
    }

    //get the list of fields for the object objectName
    @AuraEnabled(cacheable=true)
    public static List<CustomPathSteps__mdt> getCustomMetadataFields(String sObjName) {
        // Remplacez 'YourCustomMetadataType__mdt' par le nom de votre CMT

        List<CustomPathSteps__mdt> metadataFields = [
            SELECT object__r.ObjectName__c, object__r.Active__c, object__r.StatusField__c, stepName__c, stepNum__c, GuideSelling__c, (SELECT FieldApiName__c FROM CustomPathFields__r)
            FROM CustomPathSteps__mdt
            WHERE object__r.Active__c = TRUE AND object__r.ObjectName__c =: sObjName
            ORDER BY stepNum__c ASC
        ];
        return metadataFields;
    }

    //get current current object status field value
    @AuraEnabled(cacheable=true)
    public static String getCurrentObjectStatus(String objectName, String recordId, string statusField) {
        String query = 'SELECT ' + statusField + ' FROM ' + objectName + ' WHERE Id = :recordId';
        SObject record = Database.query(query);
        return (String) record.get(statusField);
    }

    //get the fields values of the object objectName from a list of fields and for a specific recordId
    
    @AuraEnabled
    public static String getFieldsValues(String objectName, String fieldsValuesJson, String recordId) {

        system.debug('fieldsValuesJson'+ fieldsValuesJson);
        List<FieldWrapper> fieldValues = (List<FieldWrapper>) JSON.deserialize(fieldsValuesJson, List<FieldWrapper>.class);

        system.debug('fieldValues'+ JSON.serialize(fieldValues));
        String query = 'SELECT ';
        for (FieldWrapper fw : fieldValues) {
            query += fw.FieldApiName + ', ';
        }
        query = query.removeEnd(', ') + ' FROM ' + objectName + ' WHERE Id = :recordId';
        
        SObject record = Database.query(query);
        for (FieldWrapper fw : fieldValues) {
            fw.Value = String.valueOf(record.get(fw.FieldApiName));
        }

        return Json.serialize(fieldValues);
    }

    class FieldWrapper {
        public String FieldApiName;
        public String Value;
    }
}